<?php
namespace App\Models;


use Nette\Application\Application;
use Nette\Mail\Mailer;
use Nette\Mail\Message;

class EmailService
{
    const PRIORITY_HIGH = 1;
    const PRIORITY_LOW = 0;

    /** @var Application $application */
    protected Application $application;

    /** @var Mailer */
    protected Mailer $smtpMailer;

    /** @var string */
    protected string $emailFrom;

    public function __construct(string $emailFrom, Application $application, Mailer $smtpMailer)
    {
        $this->application = $application;
        $this->smtpMailer = $smtpMailer;
        $this->emailFrom = $emailFrom;
    }

    /**
     * Creates new message with default params
     *
     * @return Message
     */
    public function createMessage(): Message
    {
        $message = new Message();
        $message->setFrom($this->emailFrom,'MIS');
        return $message;
    }

    /**
     * Renders email body from template
     *
     * @param Message $message
     * @param string $templatePath
     * @param array $templateVariables
     * @param null|string $basePath
     * @throws \Throwable
     */
    public function setBodyFromTemplate(Message $message, string $templatePath, array $templateVariables, ?string $basePath = null): void
    {
        $latte = new \Latte\Engine;

        $defaultStyles = '<style>'.file_get_contents(__DIR__.'/../../assets/styles/emailStyles.css').'</style>';

        $latte->addExtension(new \Nette\Bridges\ApplicationLatte\UIExtension($this->application->getPresenter())); // Kromě jiných zaregistruje makro link a plink

        $footer = '<br><br><p style="text-align: right"><small>Generated by User Management</small></p>';

        $message->setHtmlBody($defaultStyles.$latte->renderToString($templatePath, $templateVariables).$footer,$basePath);
    }

    /**
     * Sends message
     *
     * @param Message $message
     * @throws \Exception
     */
    public function sendMessage(Message $message): void
    {
        $message->setSubject('[USER MANAGER] - '.$message->getSubject());
        $this->smtpMailer->send($message);
    }
}